name: Format code with gofmt
description: Format code with gofmt
inputs:
  path:
    description: Path to the code to format
    required: false
    default: ./
outputs:
  report:
    description: 'A report of the the output'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}