name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    # Run from a specific container with go and protoc already installed
    container: duartemralves/maestro.test-workflow:latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Grpc
        run: |
          chmod +x ./scripts/genpb.sh
          ./scripts/genpb.sh

      - name: Build
        run: go build -v ./...

      - name: Test internal package
        run: go test ./internal/...